schema = 3

[mod]
  [mod."cloud.google.com/go"]
    version = "v0.31.0"
    hash = "sha256-t9FOG7yofPY19JE9xZxKlGYfNJvShJib+OEuLF7HWV4="
  [mod."github.com/int128/oauth2cli"]
    version = "v1.0.0"
    hash = "sha256-8+Q1UvxCVdm5TtTbnscWpHVPV+X15M9/PPUjZN01AUc="
  [mod."github.com/jessevdk/go-flags"]
    version = "v1.4.0"
    hash = "sha256-5tg5rdiLEbI53DAwp3Yps1y/6e9m9AcgzX3No4wE9dY="
  [mod."github.com/lestrrat-go/backoff"]
    version = "v0.0.0-20180409035020-828830ec1d9a"
    hash = "sha256-aJcubap/uQf/G/sRb0kjRv3fGB60blzOb4VZUxyypUg="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.0.0"
    hash = "sha256-eGmBNNTuDSMwicjTNgB54IEJuK1tgOLDJ3NHTpQCHzg="
  [mod."github.com/pkg/browser"]
    version = "v0.0.0-20180916011732-0a3d74bf9ce4"
    hash = "sha256-LOwoCHXSkhpTRBFgEa9eiRKnqP7DKBJgTceGUTefZlM="
  [mod."github.com/pkg/errors"]
    version = "v0.8.0"
    hash = "sha256-5d5y6os/w8geLyptFuf4DL66xQ4YD9qmoeLCF441MQA="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20181029044818-c44066c5c816"
    hash = "sha256-jrD7nFhA3Vv0q8BCtFhE68vJQsbDEai3BK0Eusjh/FU="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20181031022657-8527f56f7107"
    hash = "sha256-+IKebEw27GsltX03EXG/xsYj7FlxO3zsMLdSrsiTymw="
  [mod."google.golang.org/api"]
    version = "v0.0.0-20181101000641-61ce27ee8154"
    hash = "sha256-PTpBiG7bQW447Ihpf2xh30aKXfZkgjK8hLhJQOivo0U="
  [mod."gopkg.in/check.v1"]
    version = "v0.0.0-20161208181325-20d25e280405"
    hash = "sha256-1w5mgYaZUC52uzDnpXXVqle/9AVkH4WePSrQFOVANUw="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.2.1"
    hash = "sha256-QY+DRctY7JryX+Hwtx2p1ThfmK9Zr6OZpu2JS4XOkjc="
